name: jarbas
description: Assistente de voz completo para Android
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0
  flutter_foreground_task: ^8.0.0
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
